### ISSUE TITLE
Plugin is not working in actual :(

### ISSUE THREAD

**Issue by procontentxyz** [woocommerce/action-scheduler-admin#23]
I have just installed action scheduler admin plugin from your repo on my site.

But its not showing any option to setup. however, there is a plugin page in Analytics but when I click on that there is no option to add or set up any hook/action with schedule.

Please make this plugin fully working. Because it is need of hour this is one which is is needed by most of the people as of now.

Thank you for your work and hoping this to be done as soon as possible

**Comment by rrennick** [comment]
> when I click on that there is no option to add or set up any hook/action with schedule.

This plugin only allows viewing Scheduled Actions. See `Scheduling an Action` on https://actionscheduler.org/usage/.

> Please make this plugin fully working.

To use this plugin you need to build it as described in https://github.com/woocommerce/action-scheduler-admin/blob/master/README.md. At some point in the future we hope to incorporate this into Action Scheduler itself.
